# Generated by Django 4.0.1 on 2022-03-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori', '0002_altkategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='İsBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_isim', models.CharField(max_length=100)),
                ('fiyat', models.IntegerField()),
                ('resim', models.ImageField(upload_to='is')),
                ('is_aciklama', models.TextField()),
                ('is_baslangic', models.DateField()),
                ('is_bitis', models.DateField()),
                ('alt_kategori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kategori.altkategori')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kategori.kategori')),
            ],
        ),
    ]
