# Generated by Django 4.0.1 on 2022-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇sbilgileri',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
