# Generated by Django 4.0.1 on 2022-03-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0002_i̇sbilgileri_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇sbilgileri',
            name='resim',
            field=models.ImageField(upload_to='uploads/is'),
        ),
    ]
