# Generated by Django 4.0.1 on 2022-03-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0003_alter_i̇sbilgileri_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇sbilgileri',
            name='resim',
            field=models.ImageField(upload_to='is'),
        ),
    ]
