# Generated by Django 4.0.1 on 2022-03-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0005_alter_i̇sbilgileri_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇sbilgileri',
            name='fiyat',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
