# Generated by Django 4.0.1 on 2022-03-25 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0006_alter_i̇sbilgileri_fiyat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i̇sbilgileri',
            name='resim',
        ),
        migrations.CreateModel(
            name='Is_Fotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='is')),
                ('is_bilgi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='isler.i̇sbilgileri')),
            ],
        ),
    ]
