# Generated by Django 4.0.1 on 2022-03-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0008_i̇sbilgileri_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇sbilgileri',
            name='resim1',
            field=models.ImageField(null=True, upload_to='is_fotograf'),
        ),
        migrations.AddField(
            model_name='i̇sbilgileri',
            name='resim2',
            field=models.ImageField(null=True, upload_to='is_fotograf'),
        ),
        migrations.AddField(
            model_name='i̇sbilgileri',
            name='resim3',
            field=models.ImageField(null=True, upload_to='is_fotograf'),
        ),
        migrations.DeleteModel(
            name='Is_Fotograf',
        ),
    ]
