# Generated by Django 4.0.1 on 2022-03-25 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0010_i̇sgereksinimleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici_Gereksinim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gereksinim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='isler.i̇sgereksinimleri')),
                ('is_bilgi', models.ManyToManyField(to='isler.İsBilgileri')),
            ],
        ),
    ]
