# Generated by Django 4.0.1 on 2022-03-25 23:29

from django.db import migrations, models
import django.db.models.deletion
import isler.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0011_kullanici_gereksinim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici_gereksinim',
            name='gereksinim',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name=isler.models.İsGereksinimleri),
        ),
        migrations.RemoveField(
            model_name='kullanici_gereksinim',
            name='is_bilgi',
        ),
        migrations.AddField(
            model_name='kullanici_gereksinim',
            name='is_bilgi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='isler.i̇sbilgileri'),
        ),
    ]
