# Generated by Django 4.0.1 on 2022-03-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0012_alter_kullanici_gereksinim_gereksinim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_isim', models.CharField(max_length=100)),
                ('fiyat', models.PositiveSmallIntegerField(default=1)),
                ('is_aciklama', models.TextField()),
            ],
        ),
    ]
