# Generated by Django 4.0.1 on 2022-04-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0013_deneme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
