# Generated by Django 4.0.1 on 2022-04-15 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0010_alter_kullanici_telefon'),
        ('isler', '0014_delete_deneme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basvuru_Kayitlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alan', models.CharField(max_length=100)),
                ('secim_aciklama', models.TextField()),
                ('is_bilgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isler.i̇sbilgileri')),
                ('kullanici_bilgi', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profil.kullanici')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
