# Generated by Django 4.0.1 on 2022-04-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_alter_kullanici_telefon'),
        ('isler', '0015_basvuru_kayitlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basvuru_kayitlari',
            name='kullanici_bilgi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.kullanici'),
        ),
    ]
