# Generated by Django 4.0.1 on 2022-04-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0016_alter_basvuru_kayitlari_kullanici_bilgi'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru_kayitlari',
            name='bitti',
            field=models.BooleanField(default=0),
        ),
    ]
