# Generated by Django 4.0.1 on 2022-04-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0017_basvuru_kayitlari_bitti'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru_kayitlari',
            name='secildi_mi',
            field=models.BooleanField(default=0),
        ),
    ]
