# Generated by Django 4.0.1 on 2022-04-22 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isler', '0018_basvuru_kayitlari_secildi_mi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basvuru_kayitlari',
            name='bitti',
        ),
        migrations.RemoveField(
            model_name='basvuru_kayitlari',
            name='secildi_mi',
        ),
        migrations.CreateModel(
            name='Secilen_Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secildi_mi', models.BooleanField(default=0)),
                ('is_bitti_mi', models.BooleanField(default=0)),
                ('is_bilgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isler.i̇sbilgileri')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
