# Generated by Django 4.0.1 on 2022-05-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0019_remove_basvuru_kayitlari_bitti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secilen_freelancer',
            name='basvuru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isler.basvuru_kayitlari'),
        ),
    ]
