# Generated by Django 4.0.1 on 2022-05-11 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isler', '0020_secilen_freelancer_basvuru'),
    ]

    operations = [
        migrations.AddField(
            model_name='secilen_freelancer',
            name='is_veren',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_veren', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secilen_freelancer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
