# Generated by Django 4.0.1 on 2022-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0021_secilen_freelancer_is_veren_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇sbilgileri',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='i̇sbilgileri',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='i̇sbilgileri',
            name='yayin_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
