# Generated by Django 4.0.1 on 2022-05-16 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0022_i̇sbilgileri_guncelleme_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇sbilgileri',
            name='guncelleme_tarihi',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 16, 11, 43, 40, 787309, tzinfo=utc), null=True),
        ),
    ]
