# Generated by Django 4.0.1 on 2022-05-16 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0023_alter_i̇sbilgileri_guncelleme_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇sbilgileri',
            name='guncelleme_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 11, 44, 10, 737288, tzinfo=utc), null=True),
        ),
    ]
