# Generated by Django 4.0.1 on 2022-05-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isler', '0024_alter_i̇sbilgileri_guncelleme_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇sbilgileri',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
