# Generated by Django 4.0.1 on 2022-05-16 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isler', '0025_alter_i̇sbilgileri_guncelleme_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='basvuru_kayitlari',
            name='is_veren',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isveren', to=settings.AUTH_USER_MODEL),
        ),
    ]
