# Generated by Django 4.0.1 on 2022-05-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0014_uploadfile'),
        ('isler', '0027_basvuru_kayitlari_secildi_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='secilen_freelancer',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.uploadfile'),
        ),
    ]
