# Generated by Django 4.0.1 on 2022-05-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesajlasma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
