# Generated by Django 4.0.1 on 2022-05-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0012_remove_kullanici_freelancer_mi'),
        ('mesajlasma', '0004_mesajkanali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='receiver_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='profil.kullanici'),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='sender_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='profil.kullanici'),
        ),
        migrations.AlterField(
            model_name='mesajkanali',
            name='receiver_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to='profil.kullanici'),
        ),
        migrations.AlterField(
            model_name='mesajkanali',
            name='sender_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to='profil.kullanici'),
        ),
    ]
