# Generated by Django 4.0.1 on 2022-05-16 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci_dogrulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrencidogrulama',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 18, 0, 15, 491594)),
        ),
    ]
