# Generated by Django 4.0.1 on 2022-03-13 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universite', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_profil', models.ImageField(null=True, upload_to='kullanici')),
                ('protfoy', models.ImageField(null=True, upload_to='portföy')),
                ('freelancer', models.BooleanField(default=False)),
                ('isveren', models.BooleanField(default=False)),
                ('aciklama', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('sehir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profil.sehir')),
                ('universite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profil.universite')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
