# Generated by Django 4.0.1 on 2022-03-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_remove_kullanici_protfoy_kullanici_dogum_gunu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='telefon',
            field=models.IntegerField(null=True),
        ),
    ]
