# Generated by Django 4.0.1 on 2022-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_kullanici_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yetenekler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
            ],
        ),
    ]
