# Generated by Django 4.0.1 on 2022-04-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_fotograf_kullanici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='telefon',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
