# Generated by Django 4.0.1 on 2022-04-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_alter_kullanici_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='telefon',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
