# Generated by Django 4.0.1 on 2022-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_alter_kullanici_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='freelancer_mi',
            field=models.BooleanField(default=0),
        ),
    ]
