# Generated by Django 4.0.1 on 2022-04-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0011_kullanici_freelancer_mi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='freelancer_mi',
        ),
    ]
