# Generated by Django 4.0.1 on 2022-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0012_remove_kullanici_freelancer_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='hesap_kayit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kullanici',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
