# Generated by Django 4.0.1 on 2022-05-17 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0013_kullanici_gender_kullanici_hesap_kayit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bilgi', models.IntegerField()),
                ('file', models.FileField(upload_to='is_teslim')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_upload', to=settings.AUTH_USER_MODEL)),
                ('isveren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isveren_upload', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
