# Generated by Django 4.0.1 on 2022-03-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altKategoriAd', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.kategori')),
            ],
        ),
    ]
