# Generated by Django 4.0.1 on 2022-05-18 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isler', '0028_secilen_freelancer_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaYatirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yatırılan_tutar', models.IntegerField()),
                ('yatirilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para_freelancer', to=settings.AUTH_USER_MODEL)),
                ('isveren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para_isverene', to=settings.AUTH_USER_MODEL)),
                ('yapilan_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isler.i̇sbilgileri')),
            ],
        ),
        migrations.CreateModel(
            name='ParaCekme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cekilen_tutar', models.IntegerField()),
                ('cekilme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
