# Generated by Django 4.0.1 on 2022-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('para_islemleri', '0003_toplambakiye'),
    ]

    operations = [
        migrations.AddField(
            model_name='toplambakiye',
            name='cekilen_para',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toplambakiye',
            name='odenen_para',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
