# Generated by Django 4.0.1 on 2022-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('para_islemleri', '0004_toplambakiye_cekilen_para_toplambakiye_odenen_para'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplambakiye',
            name='cekilen_para',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toplambakiye',
            name='odenen_para',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='toplambakiye',
            name='toplam_bakiye',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
