# Generated by Django 4.0.1 on 2022-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('para_islemleri', '0005_alter_toplambakiye_cekilen_para_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paracekme',
            name='iban',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
